development: &default
  adapter: postgresql
  encoding: utf8
  database: cadence_development

test:
  <<: *default
  database: cadence_test

staging:
  <<: *default
  database: cadence_staging

production:
  <<: *default
  database: cadence
